# Generated by Django 2.0 on 2019-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='название')),
                ('code', models.CharField(max_length=255, verbose_name='код')),
            ],
            options={
                'verbose_name': 'планета',
                'verbose_name_plural': 'планеты',
                'ordering': ['order'],
            },
        ),
    ]
